---
title: "Vizualization II"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork)
```

1. rnoaa = allows you to access public data
2. lines 15 - 19 --> bring data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Remember this plot...?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point()
```

## Adding Labels to Plots (USE LABS)

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  )
```

## Scales (USE `SCALE`)

Start with the same plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    trans = "sqrt" #trans = transformation (i.e., sqrt, log)
  )
```

## Color scales

### using scale_color_hue
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  ) +
  scale_color_hue(
    name = "Location", #change index for color from "name" to "locations"
    h = c(50,300)) #color scale (h = hue of the scale)
```

### using VIRIDIS for color palette/options
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  ) +
    viridis::scale_color_viridis(
      name = "Location",
      discrete = TRUE)

```

## Themes
1. move legend location
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  ) +
   viridis::scale_color_viridis(
      name = "Location",
      discrete = TRUE) +
  theme(legend.position = "bottom") #move legend from right to bottom
```

2. change the overall theme

A. option 1 (theme_minimal)
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  ) +
   viridis::scale_color_viridis(
      name = "Location",
      discrete = TRUE) +
  theme_minimal() + #theme (minimal, bw, etc)
```

B. option 2 (ggthemes)
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temperature (C)",
    y = "Max daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  ) +
   viridis::scale_color_viridis(
      name = "Location",
      discrete = TRUE) +
  ggthemes::theme_excel()
```

## Setting options

```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legened.poisiton = "bottom")) #always do this everyhwere

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

